### ISSUE TITLE
Jesus, como cadidatar?

### ISSUE THREAD

**Issue by ghost** [anabastos/mozao#1]
QUEEEEERRRPOOOO <3

**Comment by anabastos** [comment]
Olá, infelizmente o prazo de inscrição para mozão foi fechado temporáriamente na prática mas  voce ainda pode fazer um workaround básico de voltar o commit e mandar sua incrição se achar necessário.
Talvez em breve abra novamente vagas já que ainda não houve nenhum mozão selecionado.
Obrigada por caring, smak smak ❤️

**Comment by IgorHalfeld** [comment]
![dancing](https://68.media.tumblr.com/2dfc3369827df9b981e111d7fd8fc732/tumblr_mvemcyarmn1rslphyo1_400.gif)

**Comment by ghost** [comment]
Você conseguir? Não cheguei a temp ohahahaha

**Comment by IgorHalfeld** [comment]
@DrellDeveloper acho que ainda tenho uma chance!

![dancing](https://camo.githubusercontent.com/95e2fce859532f1408b83fd08e05e576099283a7/68747470733a2f2f36382e6d656469612e74756d626c722e636f6d2f32646663333336393832376466396239383165313131643766643866633733322f74756d626c725f6d76656d637961726d6e3172736c7068796f315f3430302e676966)

**Comment by ghost** [comment]
hahahaha, pena que sou programador PHP, pena.

**Comment by anabastos** [comment]
@drelldeveloper Olá. Queria informar que vamos reabrir esse ano vagas p/ mozão 2018.
Em breve teremos atualizações no repositório.
Obrigada pelo interesse

**Comment by ghost** [comment]
É serio? Jesus, tô passando mal.
