### ISSUE TITLE
Abre as inscrições ae de novo, véi!

### ISSUE THREAD

**Issue by IgorHalfeld** [anabastos/mozao#3]
![dancing](https://68.media.tumblr.com/2dfc3369827df9b981e111d7fd8fc732/tumblr_mvemcyarmn1rslphyo1_400.gif)

**Comment by ghost** [comment]
OXI! acha que é assim fácil?

**Comment by ghost** [comment]
Estou na fila hahahahahaha

**Comment by anabastos** [comment]
Proce eu abro

**Comment by ghost** [comment]
Pra eu?

**Comment by IgorHalfeld** [comment]
@drelldeveloper errrrrrouuuu

![dancing](https://camo.githubusercontent.com/95e2fce859532f1408b83fd08e05e576099283a7/68747470733a2f2f36382e6d656469612e74756d626c722e636f6d2f32646663333336393832376466396239383165313131643766643866633733322f74756d626c725f6d76656d637961726d6e3172736c7068796f315f3430302e676966)

**Comment by sergiors** [comment]
i found a bug huehue
