### ISSUE TITLE
v2018

### ISSUE THREAD

**Issue by thiagopaiva99** [anabastos/mozao#5]
Oi, vai rolar a v2018? Tenho interesse

**Comment by anabastos** [comment]
@thiagopaiva99  Vai rolar sim
Já abrimos a issue #6

**Comment by thiagopaiva99** [comment]
@anabastos Pô, podia ter rolado durante a CP :cry:

**Comment by anabastos** [comment]
@thiagopaiva99 eita
mas logo menos tem outra
